name = "mcp"
compatibility_date = "2026-07-29"

main = ".vercel/output/static/_worker.js"

[site]
bucket = ".vercel/output/static"

[[kv_namespaces]]
binding = "MCP_TASKS"
id = "a0f8491be46245fb9d6058d80309e9fe"
